### ISSUE TITLE
Full example send message

### ISSUE THREAD

**Issue by loic-hamdi** [TramontaG/WA-#1]
Hi,
Could you share a full example on how to send a message to `xxxxxxx@c.us` ?

**Comment by TramontaG** [comment]
Hi! Please note this is not an automator tool for your general purpose needs. This is a browser extension that adds new funcionality to the whatsapp web client. Since you can send messages through the whatsapp web client itself, this tool shouldn't be necessary.

If you need to programatically send messages through code, I suggest you to use [WWebJs](https://wwebjs.dev). The backbone of the whatsapp integration is the same.
